--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaPigGuy/Commando-4.0.0
build-by-default: true
branches:
- master
projects:
  Commando:
    path: ""
    model: virion
    type: library
...
